### ISSUE TITLE
REST Api POST luominen

### ISSUE THREAD

**Issue by JouniAUT** [goluart/Projekti#39]

**Comment by HMVarp** [comment]
POST lisätty

**Comment by habibur4340** [comment]
Creating a REST API POST endpoint involves defining how the server should accept and process data submissions from clients. For designing, testing, and refining this endpoint, Apidog offers an intuitive platform, making it easier to ensure the endpoint meets its functional requirements and integrates seamlessly with the rest of your API. [Apidog's](https://apidog.com/) tools can help streamline the development process, from initial design to final testing.
